services:
  - type: web
    name: api_asma-web-developer  # tu peux changer ce nom
    runtime: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start:prod"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render définit sa propre valeur, mais tu dois lire process.env.PORT dans ton code
      - key: DATABASE_URL
        sync: false  # Tu dois la définir dans le dashboard Render si elle est sensible
